use std::path::Path;

/// TOML template written by `xray init`.
const TEMPLATE: &str = r#"# xray.toml — HPC scientific Python linter configuration
# Generated by `xray init`.  Uncomment and adjust as needed.
# Run `xray --list-rules` to see all available rule IDs.
# Run `xray explain <RULE_ID>` for rationale and examples.

# ── Global rule control ────────────────────────────────────────────────────────
# Disable specific rules for the entire project.  Rule IDs are case-insensitive.
# disable = ["NP003", "IO001"]

# Lowest severity to report.  One of: "hint" | "warning" | "error".
# Overridden by --min-severity / XRAY_MIN_SEVERITY on the command line.
# min_severity = "hint"


# ── Inherit a shared config ────────────────────────────────────────────────────
# Keys set here override the inherited ones; `disable`, `severity_overrides`
# and `per_file_ignores` are merged rather than replaced, so extending a
# profile never silently drops its rules.
# Resolved relative to THIS file's directory.  Local paths only — a remote URL
# would make every lint run depend on the network and let whoever controls that
# URL change what your CI enforces.  Vendor the file and point at it instead.
# extends = "../shared/house-style.toml"


# ── Per-path rule control ──────────────────────────────────────────────────────
# Skip rules for paths matching a glob.  Use "*" to skip every rule.
# Without this the only lever is the global `disable` list above, so one noisy
# rule in one directory costs coverage across the whole project.
# [per_file_ignores]
# "**/tests/**" = ["*"]
# "notebooks/**" = ["DK004", "NP004"]


# ── Per-rule severity overrides ────────────────────────────────────────────────
# Override the default severity for individual rules.
# Valid values: "hint" | "warning" | "error"
# Example: promote XR002 to error for strict codebases, demote NP003 to hint.
# [severity_overrides]
# XR002 = "error"
# NP003 = "hint"


# ── Path control ───────────────────────────────────────────────────────────────
# Control which files are linted when you run bare `xray` with no path arguments.
# [paths]
# Files to include (glob patterns).  Default: all .py files recursively.
# include = ["**/*.py"]
#
# Files to exclude (glob patterns).  Applied after include.
# exclude = ["tests/fixtures/**", "**/vendor/**", "**/generated_*.py"]


# ── xarray rules ──────────────────────────────────────────────────────────────
[xarray]
# Treat .values access (XR002) as an error rather than a warning.
# Upgrade this if your codebase treats coordinate metadata as safety-critical.
# values_access_is_error = false


# ── dask rules ────────────────────────────────────────────────────────────────
[dask]
# Number of .compute() calls in a single file that triggers DK003.
# Lower this if your codebase should always batch computes.
# compute_call_threshold = 3


# ── numpy / pandas rules ──────────────────────────────────────────────────────
[numpy]
# Flag DataFrame.iterrows() calls (NP001).
# Disable if your project intentionally uses iterrows for small DataFrames.
# flag_iterrows = true


# ── I/O rules ─────────────────────────────────────────────────────────────────
[io]
# Flag uncompressed / unchunked storage patterns:
# np.save (IO001) and direct netCDF4.Dataset opens (IO002).
# flag_missing_compression = true


# ── HPC job scripts ───────────────────────────────────────────────────────────
# The JOB rules (JOB001-JOB005) cross-check the Python against the submission
# script that launches it: allocated cores vs. the dask cluster actually built,
# a memory request vs. an unchunked read, a GPU nobody imports a library for.
#
# They are opt-in.  Pass `--job run.sh` on the command line, or set a glob here
# so CI picks the script up without the flag.  The first match in sorted order
# is used.
#
# Parsing stays purely syntactic: `#SBATCH` / `#PBS` directives are read as
# text, the shell is never executed, and a directive xray cannot read (say
# `--cpus-per-task=$NCPUS`) simply produces no finding rather than a guess.
[job]
# script = "submit.sh"
# script = "jobs/*.sh"
"#;

/// Write `xray.toml` in the current directory.
/// Returns an error string on failure.
pub fn init(force: bool) -> Result<(), String> {
    let dest = Path::new("xray.toml");
    if dest.exists() && !force {
        return Err("xray.toml already exists.  Pass --force to overwrite.".to_string());
    }
    std::fs::write(dest, TEMPLATE).map_err(|e| format!("xray: could not write xray.toml: {e}"))?;
    println!("xray: wrote xray.toml");
    println!("  Edit it to customise rules, then run `xray` to lint your project.");
    println!("  Tip: create a .xrayignore file to exclude files or directories.");
    Ok(())
}
